apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "classify-app.fullname" . }}-postgres
  labels:
    {{- include "classify-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- include "classify-app.storageClassLine" . | nindent 2 }}
  resources:
    requests:
      storage: 5Gi
