apiVersion: v1
kind: Service
metadata:
  name: {{ include "classify-app.fullname" . }}-postgres
  labels:
    {{- include "classify-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "classify-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
