apiVersion: v1
kind: Service
metadata:
  name: {{ include "classify-app.fullname" . }}
  labels:
    {{- include "classify-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "classify-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      name: http
