apiVersion: v1
kind: Service
metadata:
  name: classify-app
  namespace: ai-demo
  labels:
    app: classify-app
spec:
  selector:
    app: classify-app
  ports:
    - port: 80
      targetPort: 8000
      name: http
